### ISSUE TITLE
RxSwiftCommunity

### ISSUE THREAD

**Issue by pgherveou** [mbalex99/FirebaseRxSwiftExtensions#4]
Thanks for this project, working like a charm!
Quick question any reason why this project is not hosted under https://github.com/RxSwiftCommunity ?

**Comment by mbalex99** [comment]
Hey @pgherveou I've just gotten swamped personally and just never got to it! I'll try to stub some time to migrate it over with a full fledged example project and test cases next week.

**Comment by mbalex99** [comment]
moved
