### ISSUE TITLE
Enhancement: Adding a createUser extension

### ISSUE THREAD

**Issue by mfstephens** [mbalex99/FirebaseRxSwiftExtensions#6]
Any chance of these methods being added?

```
createUser:password:withCompletionBlock:
createUser:password:withValueCompletionBlock:
```

Thanks!

**Comment by mbalex99** [comment]
I'll try to get to it tomorrow night!

**Comment by mbalex99** [comment]
Added an

`rx_createUser` for the `createUser:password:withValueCompletionBlock:` method.
The one that has no value callback was not included because it was redundant

**Comment by mfstephens** [comment]
awesome, thanks!
